#ifndef __ASM_R8A7794_H__
#define __ASM_R8A7794_H__

#include <linux/pm_domain.h>
#include <mach/pm-rcar.h>
#include <mach/rcar-gen2.h>

struct platform_device;

struct r8a7794_pm_domain {
	struct generic_pm_domain genpd;
	struct rcar_sysc_ch ch;
};

static inline struct rcar_sysc_ch *to_r8a7794_ch(struct generic_pm_domain *d)
{
	return &container_of(d, struct r8a7794_pm_domain, genpd)->ch;
}


/* DMA slave IDs */
enum {
	RCAR_DMA_SLAVE_INVALID,
	AUDIO_DMAC_SLAVE_SCU1_TX,
	AUDIO_DMAC_SLAVE_SCU1_RX,
	AUDIO_DMAC_SLAVE_SCU2_TX,
	AUDIO_DMAC_SLAVE_SCU2_RX,
	AUDIO_DMAC_SLAVE_SCU3_TX,
	AUDIO_DMAC_SLAVE_SCU3_RX,
	AUDIO_DMAC_SLAVE_SCU4_TX,
	AUDIO_DMAC_SLAVE_SCU4_RX,
	AUDIO_DMAC_SLAVE_SCU5_TX,
	AUDIO_DMAC_SLAVE_SCU5_RX,
	AUDIO_DMAC_SLAVE_SCU6_TX,
	AUDIO_DMAC_SLAVE_SCU6_RX,
	AUDIO_DMAC_SLAVE_SSI0_TX,
	AUDIO_DMAC_SLAVE_SSI0_RX,
	AUDIO_DMAC_SLAVE_SSI1_TX,
	AUDIO_DMAC_SLAVE_SSI1_RX,
	AUDIO_DMAC_SLAVE_SSI2_TX,
	AUDIO_DMAC_SLAVE_SSI2_RX,
	AUDIO_DMAC_SLAVE_SSI3_TX,
	AUDIO_DMAC_SLAVE_SSI3_RX,
	AUDIO_DMAC_SLAVE_SSI4_TX,
	AUDIO_DMAC_SLAVE_SSI4_RX,
	AUDIO_DMAC_SLAVE_SSI5_TX,
	AUDIO_DMAC_SLAVE_SSI5_RX,
	AUDIO_DMAC_SLAVE_SSI6_TX,
	AUDIO_DMAC_SLAVE_SSI6_RX,
	AUDIO_DMAC_SLAVE_SSI7_TX,
	AUDIO_DMAC_SLAVE_SSI7_RX,
	AUDIO_DMAC_SLAVE_SSI8_TX,
	AUDIO_DMAC_SLAVE_SSI8_RX,
	AUDIO_DMAC_SLAVE_SSI9_TX,
	AUDIO_DMAC_SLAVE_SSI9_RX,
	AUDIO_DMAC_SLAVE_SSIU0_TX,
	AUDIO_DMAC_SLAVE_SSIU0_RX,
	AUDIO_DMAC_SLAVE_SSIU1_TX,
	AUDIO_DMAC_SLAVE_SSIU1_RX,
	AUDIO_DMAC_SLAVE_SSIU2_TX,
	AUDIO_DMAC_SLAVE_SSIU2_RX,
	AUDIO_DMAC_SLAVE_SSIU3_TX,
	AUDIO_DMAC_SLAVE_SSIU3_RX,
	AUDIO_DMAC_SLAVE_SSIU4_TX,
	AUDIO_DMAC_SLAVE_SSIU4_RX,
	AUDIO_DMAC_SLAVE_SSIU5_TX,
	AUDIO_DMAC_SLAVE_SSIU5_RX,
	AUDIO_DMAC_SLAVE_SSIU6_TX,
	AUDIO_DMAC_SLAVE_SSIU6_RX,
	AUDIO_DMAC_SLAVE_SSIU7_TX,
	AUDIO_DMAC_SLAVE_SSIU7_RX,
	AUDIO_DMAC_SLAVE_SSIU8_TX,
	AUDIO_DMAC_SLAVE_SSIU8_RX,
	AUDIO_DMAC_SLAVE_SSIU9_TX,
	AUDIO_DMAC_SLAVE_SSIU9_RX,
	AUDIOPP_DMAC_SLAVE_SCU1_TO_SSI1,
	AUDIOPP_DMAC_SLAVE_SCU2_TO_SSI2,
	AUDIOPP_DMAC_SLAVE_SCU3_TO_SSI3,
	AUDIOPP_DMAC_SLAVE_SCU4_TO_SSI4,
	AUDIOPP_DMAC_SLAVE_SCU5_TO_SSI5,
	AUDIOPP_DMAC_SLAVE_SCU6_TO_SSI6,
	AUDIOPP_DMAC_SLAVE_SSI1_TO_SCU1,
	AUDIOPP_DMAC_SLAVE_SSI2_TO_SCU2,
	AUDIOPP_DMAC_SLAVE_SSI3_TO_SCU3,
	AUDIOPP_DMAC_SLAVE_SSI4_TO_SCU4,
	AUDIOPP_DMAC_SLAVE_SSI5_TO_SCU5,
	AUDIOPP_DMAC_SLAVE_SSI6_TO_SCU6,
	AUDIOPP_DMAC_SLAVE_CMD0_TO_SSI0,
};

void r8a7794_add_standard_devices(void);
void r8a7794_add_dt_devices(void);
void r8a7794_clock_init(void);
void r8a7794_pinmux_init(void);
void r8a7794_pm_init(void);
void r8a7794_init_early(void);
void r8a7794_timer_init(void);
extern struct smp_operations r8a7794_smp_ops;

#ifdef CONFIG_PM
extern void __init r8a7794_init_pm_domains(void);
#else
static inline void r8a7794_init_pm_domains(void) {}
#endif /* CONFIG_PM */

void r8a7794_module_reset(unsigned int n, u32 bits, int usecs);

#endif /* __ASM_R8A7794_H__ */
